### PR TITLE
Create NickPullTest

### PR DESCRIPTION
**Pull request by NickThom**
Created NickPullTest and put text in it

### CODE REVIEW

**Review by cashuaa — APPROVED** [review]

**Review by jmontesoca — APPROVED** [review]
Approved

**Review by michel-gabriel — CHANGES_REQUESTED** [review]
say gabe is cool

**Review by cashuaa — APPROVED** [review]

**Review by cashuaa — APPROVED** [review]

**Review by cashuaa — CHANGES_REQUESTED** [review]
say cash is cooler than Gabe

**Review by michel-gabriel — APPROVED** [review]

**Review by cashuaa — APPROVED** [review]

**Comment by NickThom** [comment]
I don't want to make those changes for political reasons

**Pull request merged**
